<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{0a9ebfbe-586c-4bb2-b52a-ab34082263a2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbAPS_Prog:FB_APS_Prog;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbAPS_Prog();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>